openinfradays/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.flatpages import views
from django.urls import path

from .views import index, ProgramList, schedule_page, login, process_login, \
    HandOnLabList, ProgramDetail, sponsors, SponsorDetail


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    url(r'^$', index, name='index'),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^index.html', index, name='index_html'),
    url(r'^sponsors.html', sponsors, name='sponsors'),
    url(r'^programs', ProgramList.as_view(), name="programs"),
    url(r'^program/(?P<pk>\d+)$', ProgramDetail.as_view(), name='program'),
    url(r'^sponsor/(?P<slug>\w+)$', SponsorDetail.as_view(), name='sponsor'),
    url(r'^schedule', schedule_page),
    url(r'^hand-on-lab', HandOnLabList.as_view()),
    url(r'^login/$', login),
    url(r'^login/process/(?P<token>[a-z0-9\-]+)$', process_login),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^invite', views.invite, name='invite'),
    url(r'^check', views.check, name='check'),
    url(r'^process', views.register_invite_ticket, name='register_invite_ticket'),
]

openinfradays/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.template.defaultfilters import date as _date
from uuid import uuid4


class AuthToken(models.Model):
    token = models.CharField(max_length=64)
    email = models.EmailField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.token = str(uuid4())
        super(AuthToken, self).save(*args, **kwargs)


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    company = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)


class Speaker(models.Model):
    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100, db_index=True)
    organization = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=255, db_index=True,
                              null=True, blank=True)
    image = models.ImageField(upload_to='speaker', null=True, blank=True)
    desc = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class ProgramCategory(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ProgramDate(models.Model):
    day = models.DateField()

    def __str__(self):
        return _date(self.day, "Y-m-d (D)")


class ProgramTime(models.Model):
    name = models.CharField(max_length=100)
    begin = models.TimeField()
    end = models.TimeField()
    day = models.ForeignKey(ProgramDate, null=True, blank=True,
                            on_delete=True)

    def __meta__(self):
        ordering = ['begin']

    def __str__(self):
        return '%s - %s (%s)' % (self.begin, self.end, self.day)


class Program(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    brief = models.TextField(null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    slide_url = models.CharField(max_length=255, null=True, blank=True)
    video_url = models.CharField(max_length=255, null=True, blank=True)

    date = models.ForeignKey(ProgramDate, null=True, blank=True,
                             on_delete=True)
    room = models.ForeignKey(Room, null=True, on_delete=models.SET_NULL)
    times = models.ManyToManyField(ProgramTime, blank=True)
    category = models.ForeignKey(ProgramCategory, null=True, blank=True,
                                 on_delete=True)
    speaker = models.ForeignKey(Speaker, null=True, on_delete=False)

    def get_url(self):
        return reverse('program', args=[self.id])

    def get_times(self):
        times = self.times.all()

        if times:
            return '%s - %s' % (times[0].begin.strftime("%H:%M"),
                                times[len(times) - 1].end.strftime("%H:%M"))
        else:
            return "Not arranged yet"


class SponsorLevelManager(models.Manager):
    def get_queryset(self):
        return super(SponsorLevelManager, self).get_queryset()\
            .all().order_by('order')


class SponsorLevel(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    order = models.IntegerField(default=1)

    objects = SponsorLevelManager()

    def __str__(self):
        return self.name


class Sponsor(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, null=True)
    image = models.ImageField(upload_to='sponsor', null=True, blank=True)
    url = models.CharField(max_length=1024, null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    level = models.ForeignKey(SponsorLevel, null=True, blank=True,
                              on_delete=models.SET_NULL)

    class Meta:
        ordering = ['id']

    def get_url(self):
        return reverse('sponsor', args=[self.id])

    def __str__(self):
        return self.name

openinfradays/forms.py
from django import forms
from django.utils.translation import ugettext as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class EmailLoginForm(forms.Form):
    email = forms.EmailField(
        max_length=255,
        label='',
        widget=forms.TextInput(attrs={
            'placeholder': 'Email address',
            'class': 'form-control',
        })
    )

    def __init__(self, *args, **kwargs):
        super(EmailLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', _('Login')))

    def clean(self):
        cleaned_data = super(EmailLoginForm, self).clean()
        return cleaned_data

openinfradays/views.py
from django.contrib.auth import login as user_login, logout as user_logout
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django.utils.translation import ugettext as _
from .email import send_auth_email
from .models import ProgramCategory, AuthToken, Profile, Program, Sponsor
from .forms import EmailLoginForm


def index(request):
    return render(request, 'index2.html')


def sponsors(request):
    return render(request, 'sponsor_base.html')


def schedule_page(request):
    return render(request, 'schedule.html')


class ProgramList(ListView):
    model = ProgramCategory
    template_name = "program.html"


class ProgramDetail(DetailView):
    model = Program


class SponsorDetail(DetailView):
    model = Sponsor


class HandOnLabList(ListView):
    model = ProgramList
    template_name = "hand_on_lab.html"


def login(request):
    if request.method == "POST":
        form = EmailLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']

            # Delete existed token
            AuthToken.objects.filter(email=email).delete()

            token = AuthToken(email=email)
            token.save()

            if send_auth_email(request, token):
                return render(request, 'login_sendmail.html')
            else:
                return render(request, 'login_sendmail_fail.html')
    return render(request, 'login.html', {
        'form': EmailLoginForm(),
        'title': _('Login'),
    })


def process_login(request, token):
    # Create user automatically by email as id, token as password
    try:
        auth_token = AuthToken.objects.get(token=token)
    except ObjectDoesNotExist:
        return redirect(reverse('index'))

    try:
        email = auth_token.email
        user = User.objects.get(email=email)
    except ObjectDoesNotExist:
        user = User.objects.create_user(email, email, token)
        user.save()

        profile = Profile(user=user)
        profile.save()

    user.backend = 'django.contrib.auth.backends.ModelBackend'
    user_login(request, user)
    return redirect(reverse('index'))

openinfradays/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>{% trans "OpenInfraDays Korea 2018" %}</title>

        <!-- Opengraph tag -->
        <meta property="og:site_name" content="{% trans "OpenInfra Days Korea 2018" %}">
        <meta property="og:title" content="{% block og-title %}{% trans "OpenInfra Days Korea 2018" %}{% endblock %}">
        <meta property="og:image" content="{{ domain }}{% block og-image %}{% static "img/og_img.png" %}{% endblock %}">
        <meta property="og:url" content="{{ domain }}{{ request.path }}">
        <meta property="og:description" content="{% block og-desc %}{% trans "OpenInfra Days Korea 2018" %}{% endblock %}">

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}"/>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
        <link rel="icon" href="{% static "img/favicon.ico" %}" type="imopenstack_2017-07-13_0155.JPGage/x-icon">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>
        <!-- Header -->
        <header id="header" class="header-nav">
            <div class="container">

                <div class="navbar-header">
                    <!-- Logo -->
                    <div class="navbar-brand">
                        <a class="logo" href="{% url "index" %}">
                            <img src="{% static "img/logo-alt.png" %}" alt="logo">
                        </a>
                    </div>
                    <!-- /Logo -->

                    <!-- Mobile toggle -->
                    <button class="navbar-toggle">
                        <span></span>
                    </button>
                    <!-- /Mobile toggle -->
                </div>

                <!-- Navigation -->
                {% block nav %}{% include "nav.html" %}{% endblock %}
                <!-- /Navigation -->

            </div>
        </header>
        <!-- /Header -->
        {% block content %}{% endblock %}
		<!-- Footer -->
		<footer id="footer" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- footer logo -->
					<div class="col-md-6">
						<div class="footer-logo">
							<a class="logo" href="index.html">
								<img src="{% static "img/logo.png" %}" alt="logo">
							</a>
						</div>
					</div>
					<!-- footer logo -->

				</div>
				<!-- /row -->

				<!-- row -->
				<div id="bottom-footer" class="row">

					<!-- social -->
					<div class="col-md-4 col-md-push-8">
						<ul class="footer-social">
							<li><a href="https://www.facebook.com/groups/openstack.kr/" class="facebook"><i class="fa fa-facebook"></i></a></li>
							<li><a href="https://www.youtube.com/c/OpenStackKoreaGroup" class="youtube"><i class="fa fa-youtube"></i></a></li>
						</ul>
					</div>
					<!-- /social -->

					<!-- copyright -->
					<div class="col-md-8 col-md-pull-4">
						<div class="footer-copyright">
							<span>&copy; Copyright 2018. All Rights Reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="sm">Colorlib</a></span>
						</div>
					</div>
					<!-- /copyright -->

				</div>
				<!-- row -->

			</div>
			<!-- /container -->

		</footer>
		<!-- /Footer -->

		<!-- preloader -->
		<div id='preloader'><div class='preloader'></div></div>
		<!-- /preloader -->


		<!-- jQuery Plugins -->
		<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/main.js" %}"></script>

	</body>
</html>

openinfradays/templates/contact.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>HTML Education Template</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="css/bootstrap.min.css"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="css/font-awesome.min.css">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="css/style.css"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>

		<!-- Header -->
		<header id="header">
			<div class="container">

				<div class="navbar-header">
					<!-- Logo -->
					<div class="navbar-brand">
						<a class="logo" href="index.html">
							<img src="./img/logo.png" alt="logo">
						</a>
					</div>
					<!-- /Logo -->

					<!-- Mobile toggle -->
					<button class="navbar-toggle">
						<span></span>
					</button>
					<!-- /Mobile toggle -->
				</div>

				<!-- Navigation -->
				<nav id="nav">
					<ul class="main-menu nav navbar-nav navbar-right">
						<li><a href="index.html">Home</a></li>
						<li><a href="#">About</a></li>
						<li><a href="#">Courses</a></li>
						<li><a href="blog.html">Blog</a></li>
						<li><a href="contact.html">Contact</a></li>
					</ul>
				</nav>
				<!-- /Navigation -->

			</div>
		</header>
		<!-- /Header -->

		<!-- Hero-area -->
		<div class="hero-area section">

			<!-- Backgound Image -->
			<div class="bg-image bg-parallax overlay" style="background-image:url(./img/page-background.jpg)"></div>
			<!-- /Backgound Image -->

			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="index.html">Home</a></li>
							<li>Contact</li>
						</ul>
						<h1 class="white-text">Get In Touch</h1>

					</div>
				</div>
			</div>

		</div>
		<!-- /Hero-area -->

		<!-- Contact -->
		<div id="contact" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- contact form -->
					<div class="col-md-6">
						<div class="contact-form">
							<h4>Send A Message</h4>
							<form>
								<input class="input" type="text" name="name" placeholder="Name">
								<input class="input" type="email" name="email" placeholder="Email">
								<input class="input" type="text" name="subject" placeholder="Subject">
								<textarea class="input" name="message" placeholder="Enter your Message"></textarea>
								<button class="main-button icon-button pull-right">Send Message</button>
							</form>
						</div>
					</div>
					<!-- /contact form -->

					<!-- contact information -->
					<div class="col-md-5 col-md-offset-1">
						<h4>Contact Information</h4>
						<ul class="contact-details">
							<li><i class="fa fa-envelope"></i>Educate@email.com</li>
							<li><i class="fa fa-phone"></i>122-547-223-45</li>
							<li><i class="fa fa-map-marker"></i>4476 Clement Street</li>
						</ul>

						<!-- contact map -->
						<div id="contact-map"></div>
						<!-- /contact map -->

					</div>
					<!-- contact information -->

				</div>
				<!-- /row -->

			</div>
			<!-- /container -->

		</div>
		<!-- /Contact -->

		<!-- Footer -->
		<footer id="footer" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- footer logo -->
					<div class="col-md-6">
						<div class="footer-logo">
							<a class="logo" href="index.html">
								<img src="./img/logo.png" alt="logo">
							</a>
						</div>
					</div>
					<!-- footer logo -->

					<!-- footer nav -->
					<div class="col-md-6">
						<ul class="footer-nav">
							<li><a href="index.html">Home</a></li>
							<li><a href="#">About</a></li>
							<li><a href="#">Courses</a></li>
							<li><a href="blog.html">Blog</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
					<!-- /footer nav -->

				</div>
				<!-- /row -->

				<!-- row -->
				<div id="bottom-footer" class="row">

					<!-- social -->
					<div class="col-md-4 col-md-push-8">
						<ul class="footer-social">
							<li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
							<li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<!-- /social -->

					<!-- copyright -->
					<div class="col-md-8 col-md-pull-4">
						<div class="footer-copyright">
							<span>&copy; Copyright 2018. All Rights Reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a></span>
						</div>
					</div>
					<!-- /copyright -->

				</div>
				<!-- row -->

			</div>
			<!-- /container -->

		</footer>
		<!-- /Footer -->

		<!-- preloader -->
		<div id='preloader'><div class='preloader'></div></div>
		<!-- /preloader -->


		<!-- jQuery Plugins -->
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
		<script type="text/javascript" src="js/google-map.js"></script>
		<script type="text/javascript" src="js/main.js"></script>

	</body>
</html>

openinfradays/templates/hand_on_lab.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="row">
            <h1>{% trans "Hand-On-Lab" %}</h1>
        </div>
        <div class="row">
            {% if not object_list %}
                <p>준비중입니다.</p>
            {% endif %}
        </div>
        {% for obj in object_list %}
            <a href="#{{ obj.slug }}">
              <h3 id="{{ obj.slug }}" class="category-title" >
                {{ obj.name }}
              </h3>
            </a>
            <hr>
            <ul class="item-list">
                {% for program in obj.program_set.all %}
                    <li class="program-list-title">
                    <a href="{{ program.get_absolute_url }}">{{ program.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}

<!-- Home -->
<div id="home" class="hero-area">

    <!-- Backgound Image -->
    <div class="bg-image bg-parallax overlay" style="background-image:url({% static "img/home-background.jpg" %})"></div>
    <!-- /Backgound Image -->

    <div class="home-wrapper">
        <div class="container">

            <div class="row section-header">
                <h1 class="white-text">OpenInfra Days Korea 2018</h1>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p class="lead white-text">
                        <span class="small col-sm-1 align-middle">[Theme]</span>
                        {% trans "Main-Description" %}
                    </p>
                    <p class="lead white-text">
                        <span class="small col-sm-1 align-middle">[Date] </span>
                        {% trans "Main-Date" %}
                    </p>
                    <p class="lead white-text">
                        <span class="small col-sm-1 align-middle">[Venue] </span>
                        {% trans "Main-Location" %}
                    </p>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /Home -->

<!-- About -->
<div id="about" class="section">

    <!-- container -->
    <div class="container">

        <!-- row -->
        <div class="row">

            <div class="col-md-6">
                <div class="section-header">
                    <h2>OpenInfra Days Korea 2018</h2>
                </div>

                <!-- feature -->
                <div class="feature">
                    <i class="feature-icon fa fa-flask"></i>
                    <div class="feature-content">
                        <h4>Open Infrastructure</h4>
                        <p>{% trans "Main-openinfrastructure-Desc" %}</p>
                    </div>
                </div>
                <!-- /feature -->

                <!-- feature -->
                <div class="feature">
                    <i class="feature-icon fa fa-users"></i>
                    <div class="feature-content">
                        <h4>Community</h4>
                        <p>{% trans "Main-Community-Desc" %}</p>
                    </div>
                </div>
                <!-- /feature -->

                <!-- feature -->
                <div class="feature">
                    <i class="feature-icon fa fa-comments"></i>
                    <div class="feature-content">
                        <h4>Share our experience</h4>
                        {% trans "Main-Share-Desc" %}
                    </div>
                </div>
                <!-- /feature -->

            </div>

        </div>
        <!-- row -->

    </div>
    <!-- container -->
</div>
<!-- /About -->
{% include "sponsors.html" %}

{% endblock %}

openinfradays/templates/login.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="row">
            <h1>{% trans "Login via email" %}</h1>
        </div>
        {% crispy form %}
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/login_sendmail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <h3>{% trans "One-time login url was sent to your email. Please check your inbox" %}</h3>
        </div>
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/login_sendmail_fail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <h3>{% trans "Failed to send email. Please contact to administrator(master@openinfradays.kr)" %}</h3>
        </div>
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="row">
            <h1>{% trans "Schedule" %}</h1>
        </div>
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/program.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="row">
            <h1>{% trans "Programs" %}</h1>
        </div>
        <div class="row">
            {% if not object_list %}
                <p>준비중입니다.</p>
            {% endif %}
        </div>
        {% for obj in object_list %}
            <a href="#{{ obj.slug }}">
              <h3 id="{{ obj.slug }}" class="category-title" >
                {{ obj.name }}
              </h3>
            </a>
            <hr>
            <ul class="item-list">
                {% for program in obj.program_set.all %}
                    <li class="program-list-title">
                    <a href="{{ program.get_absolute_url }}">{{ program.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/schedule.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="row">
            <h1>{% trans "Schedule" %}</h1>
            <p>준비중입니다.</p>
        </div>
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/speakers.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<!-- Home -->
<div class="hero-area section">

    <div class="container">
        <div class="row">
            <h1>{% trans "Speakers" %}</h1>
        </div>
    </div>

</div>
<!-- /Home -->
{% endblock %}

openinfradays/templates/sponsor_base.html
{% extends "base.html" %}
{% block content %}
    {% include "sponsors.html" %}
{% endblock %}

openinfradays/templates/sponsors.html
{% load i18n %}
{% load staticfiles %}

<!-- Courses -->
<div id="courses" class="section">

    <!-- container -->
    <div class="container">

        <!-- row -->
        <div class="row">
            <div class="section-header">
                <h2>{% trans "Sponsors" %}</h2>
            </div>
        </div>
        <!-- /row -->

        <!-- courses -->
        <div id="courses-wrapper">

            <!-- row -->

            {% for level in levels %}
            <div class="row">
                    <h3> {{ level.name }}</h3>
                    {% for sponsor in level.sponsor_set.all %}
                        <div class="col-md-3 col-sm-6 col-xs-6">
                            <div class="course">
                                <a href="{% url "sponsor" sponsor.slug %}" class="course-img">
                                    <img src="/media/{{ sponsor.image }}" alt="">
                                    <i class="course-link-icon fa fa-link"></i>
                                </a>
                                <a class="course-title text-center" href="#">{{ sponsor.name }}</a>
                            </div>
                        </div>
                    {% endfor %}
            </div>
            {% endfor %}
            <!-- /row -->
        </div>
    </div>
    <!-- container -->

</div>
<!-- /Courses -->